# Generated by Django 4.2.1 on 2023-05-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(unique=True)),
                ('short_url', models.SlugField(default='YmIeDIPv', unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
